### ISSUE TITLE
How to apply update after calling compute(x_true, x_pred, A, B, weights=None, mu=0.0)

### ISSUE THREAD

**Issue by OluwaseunPeter** [IshitaTakeshi/SBA#3]

**Comment by IshitaTakeshi** [comment]
It's an ordinary Gauss-Newton, so it will be like 

```python
    dposes, dpoints = sba.compute(x_true, x_pred, A, B, weights=None, mu=0.0) 
    poses = poses + dposes
    points = points + points
```

**Comment by OluwaseunPeter** [comment]
okay Thank you. I also had an error 
numpy.linalg.LinAlgError: Singular matrix
From calc_delta_a() when it called np.linalg.solve(S, e.flatten()).
Any idea about how to solve the issue ? .
Thanks once again

**Comment by IshitaTakeshi** [comment]
Maybe the matrix S has all zero row / column?
